# Generated by Django 5.1.4 on 2024-12-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canchas_deportivas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Canchas',
            new_name='Cancha',
        ),
    ]
