# Generated by Django 5.1.4 on 2024-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas_deportivas', '0002_rename_canchas_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
            preserve_default=False,
        ),
    ]
