# Generated by Django 5.1.4 on 2024-12-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas_deportivas', '0003_cancha_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='tipo_superficie',
            field=models.CharField(choices=[('Césped', 'Césped'), ('Concreto', 'Concreto'), ('Arena', 'Arena')], default='Césped', max_length=50),
            preserve_default=False,
        ),
    ]
