# Generated by Django 5.1.4 on 2024-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas_deportivas', '0004_cancha_tipo_superficie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='precio_hora',
        ),
        migrations.AddField(
            model_name='cancha',
            name='precio_hora_nocturno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cancha',
            name='precio_hora_regular',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
