# Generated by Django 5.1.4 on 2024-12-07 23:04

import canchas_deportivas.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas_deportivas', '0006_alter_cancha_tipo_superficie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, unique=True, validators=[canchas_deportivas.validators.validar_longitud_nombre])),
                ('total_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[canchas_deportivas.validators.validar_longitud_nombre]),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio_hora_nocturno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[canchas_deportivas.validators.validar_par]),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio_hora_regular',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[canchas_deportivas.validators.validar_par]),
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.PositiveIntegerField(default=1)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas_deportivas.cancha')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas_deportivas.reserva')),
            ],
        ),
    ]
